### ISSUE TITLE
Exception with autocomplete

### ISSUE THREAD

**Issue by cbrandes** [Tolc/IntelliJ_Jahia_plugin#20]
When trying to use autocomplete within brackets, i got the following exception : 

com.intellij.codeInsight.lookup.LookupElementBuilder.create(Ljava/lang/Object;)Lcom/intellij/codeInsight/lookup/LookupElementBuilder;
java.lang.NoSuchMethodError: com.intellij.codeInsight.lookup.LookupElementBuilder.create(Ljava/lang/Object;)Lcom/intellij/codeInsight/lookup/LookupElementBuilder;
	at fr.tolc.jahia.intellij.plugin.cnd.CndCompletionContributor$3.addCompletions(CndCompletionContributor.java:98)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:135)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:128)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:112)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:796)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$1000(CompletionProgressIndicator.java:90)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:778)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1$1.run(CompletionThreading.java:93)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1.run(CompletionThreading.java:88)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.run(CompletionThreading.java:84)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

Intellij version : 14.1.2

**Comment by Tolc** [comment]
Can I get the portion of code that caused this?

**Comment by cbrandes** [comment]
Just open a new cnd file, create one node type, add a property name, open a bracket for property type, ctrl-space for completion and there you got the exception in Event Log

![image](https://cloud.githubusercontent.com/assets/6814629/20830011/fc10518c-b87e-11e6-96b8-44dc3ef2c775.png)

**Comment by Tolc** [comment]
Alright thank you, I've just found why!
This completion API method does not exist in IntelliJ 14, I wasn't aware of that. I'm going to replace its usages with one the other methods doing the same thing that actually did exist in IntellJ 14.

You'll be able to use all the completions under IntelliJ 14 with version 1.2.1 of the plugin ;)
